package org.idnp.jetpackpagingsample

class ExampleBackendService {
    fun searchUsers(nextPageNumber: Int): List<Contacto> {
        val contactos = arrayListOf<Contacto>(Contacto(datos="Comisaria San Juan de Dios", direccion=" C. San Juan de Dios 304, Arequipa 04001"
            ,telefono=" (054)231515",tipo="Comisaria"),
            Contacto(datos=" Comisaría Palacio Viejo ", direccion= "C. Palacio Viejo 112, Arequipa 04001 " ,
                telefono= "(054) 205896", tipo="Comisaria"),
            Contacto(datos="Comisaria PNP Santa Marta", direccion= "Calle Sta. Marta 212, Arequipa 04001",
                telefono= "(054) 206259", tipo="Comisaria"),
            Contacto(datos="Comisaría Yanahuara", direccion= "Av. Ejército 341, Yanahuara 04013",
                telefono= "(054) 276444", tipo="Comisaria"),
            Contacto(datos="Comisaria Jose Luis Bustamante y Rivero",
                direccion= "Cipreses S/N, José Luis Bustamante y Rivero 04002",
                telefono= "(054) 427290",  tipo="Comisaria"),
            Contacto(datos="Policía de Turismo", direccion= "C. Jerusalén 315, Arequipa 04001", telefono= "(054) 282613",
                tipo="Comisaria"),
            Contacto(datos="POLICÍA NACIONAL", direccion= "Av. Emmel 106, Yanahuara 04013",
                telefono= "(054) 254020",  tipo="Comisaria"),
            Contacto(datos="Comisaría de Cayma", direccion= "Calle Plaza Principal de Cayma N°412, Av. Cayma, Cayma",
                telefono= "(054) 256891", tipo="Comisaria"),
            Contacto(datos="Comisaria Hunter", direccion= "Av. Brasilia N° 305, Jacobo Hunter 04011", telefono= "(054) 440307",
                tipo="Comisaria"),
            Contacto(datos="Comisaría Sachaca", direccion= "HCGP+P2W, Av. Fernandini, Sachaca 04013", telefono= "(054) 222179",
                tipo="Comisaria"),
            //          Hospitales
            Contacto(datos="Hospital Regional Honorio Delgado Espinoza",
                direccion= "Alcides Carrión, Arequipa 04002", telefono= "(054) 234597",  tipo="Centro De Salud"),
            Contacto(datos="Hospital Goyeneche", direccion= "Av. Goyeneche, Arequipa 04001",telefono= "(054) 231313",
                tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Carlos Alberto Seguin Escobedo", direccion= "JF4C+27X, Esquina de Peral y Filtro S/N, Arequipa",
                telefono= "(054) 214050",  tipo="Centro De Salud"),
            Contacto(datos="Seguro Social Essalud Arequipa", direccion= "C. Peral 555, Arequipa 04001", telefono= "(054) 226969",
                tipo="Centro De Salud"),
            Contacto(datos="Hospital III Yanahuara EsSalud", direccion= "JF34+56M, Av. Garaycochea, Arequipa 04013",
                telefono= "(054) 226969",  tipo="Centro De Salud"),
            Contacto(datos="Es Salud", direccion="JF39+WP2, C. Ayacucho, Arequipa 04001",
                telefono= "(054) 235155",  tipo="Centro De Salud"),
            Contacto(datos="Clínica Arequipa S.A", direccion= "Francisco Bolognesi 104, Arequipa 04017",
                telefono= "(054) 599000", tipo="Centro De Salud"),
            Contacto(datos="Clínica San Juan de Dios", direccion= "Terminal Terrestre, Óvalo, Arequipa 04011",
                telefono= "913 030 100",  tipo="Centro De Salud"),
            Contacto(datos="Policlinico Barra", direccion= "Av. Emmel 235, Arequipa 04013",
                telefono= "(054) 692816",  tipo="Centro De Salud"),
            //          Bomberos
            Contacto(datos="Benemérita y Centenaria Compañía de Bomberos Arequipa 19", direccion= "C. Bolivar 120, Arequipa 04001", telefono= "(054) 241833",
                tipo="Bomberos"),
            Contacto(datos="VII COMANDANCIA DEPARTAMENTAL DE AREQUIPA CUERPO GENERAL DE BOMBEROS VOLUNTARIOS DEL PERU", direccion= "JF5C+PG8, Alto Selva Alegre 04001",
                telefono= "(054) 213333",  tipo="Bomberos"),
            //PROVINCIA - CAMANÁ
            Contacto(datos="Comisaría sectorial la pampa", direccion= "98P2+HGQ, Vía de Evitamiento, Camaná 04446",
                telefono= "(054) 505063",  tipo="Comisaria"),
            Contacto(datos="Complejo Policial Camaná", direccion= "Av. Mariscal Castilla 735, Camaná 04450", telefono= "(054) 572988",
                tipo="Comisaria"),
            Contacto(datos="Comisaria san jose",direccion= "Avenida Plaza de Armas N°150",
                telefono= "(054) 573503",
                tipo="Comisaria"),

            Contacto(datos="Comisaría san gregorio", direccion= "Calle Progreso N°437", telefono= "(054) 505199",
                tipo="Comisaria"),
            Contacto(datos="Comisaría de El Cardo",
                direccion= "97WF+R9X, Calle Comercio N° S/N, Anexo El Puente de Fierro",
                telefono= "(054) 573460",

                tipo="Comisaria"),
            //              HOSPITALES
            Contacto(datos="Hospital de Apoyo de Camaná",
                direccion= "Panamericana Sur 550, Camaná 04450",
                telefono= "(054) 571604",

                tipo="Centro De Salud"),
            Contacto(datos="Nuevo Hospital De Camaná",
                direccion= "Av 3 de Noviembre 141, Camaná 04450",
                telefono= "(054) 571604",  tipo="Centro De Salud"),
            Contacto(datos="Hospital EsSalud Camana",
                direccion= "Av 13 de Noviembre, 04446",
                telefono= "(054)571494", tipo="Centro De Salud"),
            //              BOMBEROS
            Contacto(datos="Compañía de Bomberos de Camana B-35",
                direccion= "Jr. Nicolas de Pierola 308, Camaná 04451", telefono="(054) 571021",
                tipo="Bomberos"),
            //PROVINCIA - Caravelí
            Contacto(datos="Comisaría Sectorial de Caravelí",
                direccion= "Avenida 2 de Mayo N° 809, Caravelí 04740",
                telefono= "(054) 511081",

                tipo="Comisaria"),
            Contacto(datos="Centro de Salud de Caravelí",
                direccion= "12, Caravelí 04740",
                telefono= "(054) 511089",

                tipo="Centro De Salud"),

            //PROVINCIA . CASTILLA
            Contacto(datos="CPNP Sectorial Castilla Aplao",
                direccion=  "Cll. Pardo Sn Mz.J1 Lt.14",
                telefono=  "(054)471187",

                tipo="Comisaria"),
            Contacto(datos="Comisaría PNP Protección de Carreteras Aplao",
                direccion= "Pardo Mz. K1 Lt. 4, Aplao",
                telefono= "(054) 471022",

                tipo="Comisaria"),
            //hospital
            Contacto(datos="Hospital de Aplao",
                direccion= "Av. 21 de Marzo 111, Aplao",
                telefono= "(054) 471021",

                tipo="Centro De Salud"),
            Contacto(datos="Red de Salud Castilla - Condesuyos - La Unión (RED CCU)",
                direccion= "Av. 21 de Marzo 105, Aplao",
                telefono= "(054) 471137",

                tipo="Centro De Salud"),
            Contacto(datos="Centro de Salud Orcopampa",
                direccion= "Av. Manto S/N, Orcopampa 04656",
                telefono= "(054) 582339",

                tipo="Centro De Salud"),
            //PROVINCIA - LA UNION
            Contacto(datos="Comisaria rural alca",
                direccion= "V68P+25W, Calle Plaza de Armas S/N - La union - Alca, Alca",telefono="",

                tipo="Comisaria"),
            Contacto(datos="Comisaria rural charcana",
                direccion= "QW5H+RXV, Calle Plaza de Armas S/N - La Union Charcana, Charcana",telefono="",

                tipo="Comisaria"),
            Contacto(datos="COMISARIA SECTORIAL COTAHUASI",
                direccion= "Q4Q2+6J Cotahuasi, Perú",
                telefono= "054581031",

                tipo="Comisaria"),
            //          HOSPITAL
            Contacto(datos="CS cotahuasi",
                direccion= "AV Union,Cotahuasi, la union",telefono="",

                tipo="Centro De Salud"),
            Contacto(datos="PS Characana",
                direccion="Calle manco capac,Characana,la union", telefono="",

                tipo="Centro De Salud"),
            // PROVINCIA - CONDESUYOS
            Contacto(datos="Comisaria sectorial rural chuquibamba",
                direccion= "Avenida Nicolas de Pierola N° 100 - Condesuyos - Chuquibamba",
                telefono= "(054) 474119",

                tipo="Comisaria"),
            Contacto(datos="Comisaria rural salamanca",
                direccion= "F5W8+3FJ, Avenida Salamanca S/N - Condesuyos - Salamanca, Queñuamarca",
                telefono= "945078655",

                tipo="Comisaria"),
            Contacto(datos="Comisaria minas ocoña",
                direccion= "3V59+RF7, Calle Principal S/N - Condesuyo - Rio Grande, Cunocuno",
                telefono= "957689643",

                tipo="Comisaria"),
            Contacto(datos="COMISARIA RURAL ARCATA",
                direccion= "XP5F+CQX, Arcata 04195",
                telefono= "#957689516",

                tipo="Comisaria"),
            Contacto(datos="COMISARIA RURAL YANAQUIHUA",
                direccion= "64FF+CX Yanaquihua",
                telefono= "#957690104",

                tipo="Comisaria"),
            //      HOSPITAL
            Contacto(datos="Posta Medica De Chuquibamba",
                direccion="Av Mariscal Castilla 108 A",
                telefono="(054) 474149",

                tipo="Centro De Salud"),
            Contacto(datos="Centro de Salud Yanaquihua",
                direccion="AV.Rodriguez del valle,Yanaquihua",
                telefono= "(054) 720350",

                tipo="Centro De Salud"),
            // provincia -  islay
            Contacto(datos="Comisaría Policial de Matarani",
                direccion= "Matarani 04410",
                telefono= "(054) 557016",

                tipo="Comisaria"),
            Contacto(datos="Comisaria el arenal",
                direccion= "V6H3+HJ2, Islay - Dean Valdivia, El Arenal",
                telefono= "(054) 556042",

                tipo="Comisaria"),
            Contacto(datos="Comisaria sectorial mollendo", direccion= "C. Islay 849, Mollendo 04416",
                telefono= "(054) 534242", tipo="Comisaria"),
            Contacto(datos="Comisaria la curva", direccion= "V54H+9CJ, Avenida Dean Valdivia S/N, La Curva",
                telefono= "(054) 554042", tipo="Comisaria"),
            Contacto(datos="Comisaria Alto Inclán", direccion= "XXJW+4CP, Mollendo 04416",
                telefono= "(054) 532702",tipo="Comisaria"),
            Contacto(datos="Comisaria Punta de Bombón",
                direccion= "Calle Plaza 28 de Julio S/N, Punta de Bombón",
                telefono= "(054) 553150",

                tipo="Comisaria"),
            Contacto(datos="Comisaria cocachacra",
                direccion= "Av. Libertad 824, Cocachacra 04431",
                telefono= "(054) 403067",

                tipo="Comisaria"),
            Contacto(datos="Comisaria Miramar",
                direccion= "XXFR+HMM, Mollendo 04416",
                telefono= "(054) 533053",

                tipo="Comisaria"),
            //      hospital
            Contacto(datos="Posta Medica Matarani",
                direccion= ",2W24+C9Q, Matarani 04410",
                telefono= "(054) 557118",

                tipo="Centro De Salud"),
            Contacto(datos="Hospital II Manuel de Torres Nuñez Mollendo - EsSalud",
                direccion= "Hospital Manuel Torres Munoz, Juan B. Arenas 100, Mollendo 04416",
                telefono= "(054) 226969",

                tipo="Centro De Salud"),
            Contacto(datos="Centro de salud Alto Inclán",
                direccion= "XXJV+2XQ, Mollendo 04416",
                telefono= "(054) 532331",

                tipo="Centro De Salud"),
            Contacto(datos="Puesto de Salud El Arenal",
                direccion= "El Arenal 04425",
                telefono= "(054) 556114",

                tipo="Centro De Salud"),
            //          bomberos
            Contacto(datos="Compañia de Bomberos 12",
                direccion= "XXCM+4VW, Mollendo 04416",
                telefono= "(054) 533333",

                tipo="Bomberos"),
            Contacto(datos="Compañía de Bomberos Samuel Málaga N° 144",
                direccion= "Jhon F Kennedy 206, Mollendo 04416",
                telefono= "(054) 533572",

                tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos B—209",
                direccion= "W66M+6MW, Cocachacra 04431",
                telefono= "961 968 715",

                tipo="Bomberos"),
            //provincia - caylloma
            Contacto(datos="Comisaria rural caylloma",
                direccion= "R66G+PJQ, Plaza Principal Caylloma S/N - Caylloma, Caylloma",
                telefono= "(054) 531 072",

                tipo="Comisaria"),
            Contacto(datos="Comisaria Rural PNP Chivay",
                direccion= "997X+68W, Av. Salaverry, Chivay 04145",
                telefono= "(054) 531072",

                tipo="Comisaria"),
            Contacto(datos="Comisaría huanca",
                direccion= "Calle 3 De Setiembre S/N - Caylloma - Huanca",
                telefono="",

                tipo="Comisaria"),
            //hospital
            Contacto(datos="Centro de Salud Caylloma",
                direccion= "R67H+GVG, 04190",
                telefono="",

                tipo="Centro De Salud"),
            Contacto(datos="Centro de Salud Caylloma Alta",
                direccion="R67G+368, Caylloma 04190",
                telefono="",

                tipo="Centro De Salud"),
            Contacto(datos="Centro de Salud - MINSA",
                direccion= "9C82+G6Q, Ramon Castilla, Chivay 04145",
                telefono= "950 683 783",

                tipo="Centro De Salud"),
            Contacto(datos="Posta Medica - ESSALUD",
                direccion= "9C42+FXV, 2 de Mayo, Chivay 04145",
                telefono= "(054) 531110",

                tipo="Centro De Salud"),
            Contacto(datos="Hospital Central de Majes",
                direccion= "Majes 04110",
                telefono= "987 332 969",

                tipo="Centro De Salud"),
            //bomberos
            Contacto(datos="CUERPO GENERAL DE BOMBEROS VOLUNTARIOS DEL PERÙ",
                direccion= "B-205 - EL PEDREGAL,majes,caylloma",
                telefono= "",

                tipo="Bomberos"),
            Contacto(datos="Comisaria PNP Santa Marta", direccion= "Calle Sta. Marta 212, Arequipa 04001",
                telefono= "(054) 206259", tipo="Comisaria"),

            Contacto(datos="Comisaría San Andrés - PNP",direccion=" Jirón Huallaga 876, Cercado de Lima 15001",telefono="(01) 4265825",tipo="Comisaria"),

            Contacto(datos="Comisaría Alfonso Ugarte",direccion="Av. Alfonso Ugarte 1352, Cercado de Lima 15082",telefono="3320048",tipo="Comisaria"),
            Contacto(datos="Comisaria Mirones Bajo",direccion="Jirón Pérez de Tudela 2723, Cercado de Lima 15081",telefono="(01) 5621040",tipo="Comisaria"),
            Contacto(datos="Comisaria Monserrat - PNP",direccion="Jr. Callao 891, Cercado de Lima 15001",telefono="(01) 4318023",tipo="Comisaria"),
            Contacto(datos="Comisaría Petit Thouars",direccion="Av. Petit Thouars 455, Cercado de Lima 15046",telefono=" (01) 4317553",tipo="Comisaria"),
            Contacto(datos="Comisaría de Jesús María",direccion="Av. Arnaldo Márquez 1044, Lima 15072",telefono=" (01) 3324413",tipo="Comisaria"),
            Contacto(datos="Comisaria Santa Anita",direccion="Ciro Alegría 477, Cercado de Lima 15008",telefono="(01) 4782232",tipo="Comisaria"),
            Contacto(datos="Comisaría Cotabambas",direccion=" Pje. Buenaventura con, Cercado de Lima 15001",telefono="(01) 4286840",tipo="Comisaria"),
            Contacto(datos="Comisaria PNP - La Planicie de La Molina" ,direccion="Av Ricardo Elias Aparicio 7, Cercado de Lima 15026",telefono="(01) 3681871",tipo="Comisaria"),
            Contacto(datos="Comisaría Palomino",direccion="Jr. Santa Agustina Cdr. 7, Cercado de Lima",telefono="(01) 5641290",tipo="Comisaria"),
            Contacto(datos="Comisaría de Surquillo",direccion=" San Diego 401, Cercado de Lima 15047",telefono=" (01) 4459083",tipo="Comisaria"),
            Contacto(datos="Estacion de Bomberos N° 10 Salvadora Lima",direccion="WXX7+3QW, Jirón de la Unión, Cercado de Lima 15001",telefono="972 731 368",tipo="Bomberos"),
            Contacto(datos="IV Comandancia Departamental Lima",direccion=" XX2F+QG3, Jirón Junín, Cercado de Lima 15001",telefono=" (01) 3656605",tipo="Bomberos"),
            Contacto(datos="Comando Nacional de Bomberos del Perú",direccion=" Av. Gral. Salaverry 2495, San Isidro 15076",telefono="(01) 3991111",tipo="Bomberos"),
            Contacto(datos="Benemérita Heroica y Sesquicentenaria Compañía Francesa de Bomberos Voluntarios France 3",direccion="Jirón Moquegua 240, Cercado de Lima 15001",telefono=" (01) 4279161",tipo="Bomberos"),
            Contacto(datos="XXIV Comandancia Departamental Lima Sur",direccion=" Durero 284, Cercado de Lima 15037",telefono="(01) 4792838",tipo="Bomberos"),
            Contacto(datos="Compañia de bomberos B-4 ( BOMBA LIMA )",direccion="Jirón Manuel Candamo 455, Lince 15046",telefono="(01) 4716442",tipo="Bomberos"),
            Contacto(datos="Compañía de Bomberos Voluntarios Cosmopolita 11",direccion="Lima, Claudio Galeno 200, San Borja 15036",telefono="Lima, Claudio Galeno 200, San Borja 15036",tipo="Bomberos"),
            Contacto(datos="Bomberos Internacional 14",direccion="WXR3+3PV, Jirón Rebeca Oquendo, Cercado de Lima 15083",telefono=" (01) 4231100",tipo="Bomberos"),
            Contacto(datos="Garibaldi N° 6 - Bomberos",direccion=" Av. Defensores del Morro 298, Lima 15064",telefono="(01) 4670729",tipo="Bomberos"),
            Contacto(datos="Compañía de Bomberos ROMA 2",direccion=" Jirón Junín 568, Cercado de Lima 15001",telefono=" 992 298 004",tipo="Bomberos"),
            Contacto(datos="Compañia De Bomberos 176 El Agustino",direccion="Cotrina 203, El Agustino 15006",telefono=" (01) 3274669",tipo="Bomberos"),
            Contacto(datos="Cuartel de bomberos Victoria - 8",direccion="Jirón Manuel Cisneros, La Victoria 15033",telefono="(01) 3245858",tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos 134",direccion="Av. Monte de los Olivos S/N, Santiago de Surco, Av. Monte de los Olivos S/N, Cercado de Lima",telefono= "(01) 2746066",tipo="Bomberos"),
            Contacto(datos="Cuartel de bomberos B-83",direccion="Av. Mariscal Antonio José de Sucre 780, San Miguel 15086",telefono="(01) 4613029",tipo="Bomberos"),
            Contacto(datos="Hospital Nacional Dos De Mayo",direccion="Parque Historia de la Medicina Peruana S/N Av. Miguel Grau 13, Cercado de Lima 15003" ,telefono="(01) 3280028",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Arzobispo Loayza",direccion="Av. Alfonso Ugarte 848, Cercado de Lima 15082",telefono="(01) 6144646",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Docente Madre Niño San Bartolomé",direccion="Av. Alfonso Ugarte 825, Cercado de Lima 15001",telefono="(01) 2010400",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Hipólito Unanue",direccion="Av. César Vallejo 1390, El Agustino 15007",telefono="(01) 3625700",tipo="Centro De Salud"),
            Contacto(datos="Hospital II Ramón Castilla",direccion="Jr. Guillermo Dansey 390, Cercado de Lima 15082",telefono="950 083 385",tipo="Centro De Salud"),
            Contacto(datos="Hospital Edgardo Rebagliati - CENTRO DE EMERGENCIA",direccion=" Av. Edgardo Rebagliati 83, Cercado de Lima 15072",telefono="(01) 4118000",tipo="Centro De Salud"),
            Contacto(datos="Hospital Edgardo Rebagliati Martins",direccion="Av. Edgardo Rebagliati 490, Jesús María 15072",telefono="(01) 2654901",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Docente Madre Niño San Bartolome",direccion="Av. Alfonso Ugarte 825, Cercado de Lima 15001",telefono=" (01) 2010400",tipo="Centro De Salud"),
            Contacto(datos="HOSPITAL DE LA CARIDAD DE SAN MARTIN DE PORRES",direccion=" Jirón Callao 571, Cercado de Lima 15001",telefono="990 318 272",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Cayetano Heredia",direccion="1 CV Zac, Av. Honorio Delgado 262, San Martín de Porres 15102",telefono="(01) 4820402",tipo="Centro De Salud"),
            Contacto(datos="Hospital Suárez Angamos - EsSalud",direccion="Av. Angamos 261, Miraflores 15046",telefono="(01) 2412422",tipo="Centro De Salud"),
            Contacto(datos="SISOL Salud Mirones",direccion="XW2J+8PF, Cercado de Lima 15081",telefono="(01) 3368228",tipo="Centro De Salud"),
            Contacto(datos="Hospital Essalud I Octavio Mongrut Muñoz",direccion="Av Parque de las Leyendas 255, Cercado de Lima 15088",telefono="(01) 4118000",tipo="Centro De Salud"),
            Contacto(datos="Hospital De La Solidaridad",direccion=" XW2J+8XV, Av. Óscar R. Benavides, Cercado de Lima 15081",telefono="(01) 3368228",tipo="Centro De Salud"),
            Contacto(datos="Hospital PNP Augusto B. Leguía",direccion="C. San Germán 288, Cercado de Lima 15093",telefono=" (01) 3811869",tipo="Centro De Salud"),
            Contacto(datos="Hospital Santa Rosa",direccion="Av. Simón Bolivar 8, Pueblo Libre 15084",telefono="(01) 6158200",tipo="Centro De Salud"),
            Contacto(datos="SISOL Salud Camaná",direccion="Jirón Camaná 700, Cercado de Lima 15001",telefono=" (01) 4264619",tipo="Centro De Salud"),
            Contacto(datos="Hospital III Emergencias Grau - EsSalud",direccion=" Av. Miguel Grau Cdra 3, Cercado de Lima 15001",telefono="(01) 5728800",tipo="Centro De Salud"),
            Contacto(datos="Hospital Militar Central",direccion="Pje. Quiñones 195, Cercado de Lima 15076",telefono="(01) 2193500",tipo="Centro De Salud"),
            Contacto(datos="Clínica Anglo Americana",direccion=" C. Alfredo Salazar 350, Miraflores 15073",telefono=" (01) 6168900",tipo="Centro De Salud"),
            Contacto(datos="Hospital María Auxiliadora",direccion="Av. Miguel Iglesias 968, San Juan de Miraflores 15801",telefono="(01) 2171818",tipo="Centro De Salud"),
            Contacto(datos="Instituto Nacional de Salud del Niño - San Borja",direccion="Av. Javier Prado Este 3101, Cercado de Lima 15037",telefono="(01) 2300600",tipo="Centro De Salud"),
            Contacto(datos="Comisaria Pnp Huascar",direccion=": 5XC8+V77, Puno 21001",telefono="945 191 118",tipo="Comisaria"),
            Contacto(datos="Comisaria Sectorial PNP - Puno",direccion="Jr. Deustua 539, Puno 21001",telefono="964 792 714",tipo="Comisaria"),
            Contacto(datos="X-Macrepol PNP (Región Policial Puno)",direccion="411, Av. El Sol 495, Puno",telefono="(051) 622481",tipo="Comisaria"),
            Contacto(datos="comisaria pnp Acora",direccion="Acora 21511",telefono="964 784 583",tipo="Comisaria"),
            Contacto(datos="Comisaria PNP Caracoto",direccion="Caracoto 21108",telefono="957 687 602",tipo="Comisaria"),
            Contacto(datos="Comisaria PNP Juli",direccion="Av. Alfonso Ugarte # 832, 3S, Juli",telefono="957 688 058",tipo="Comisaria"),
            Contacto(datos="Comisaria Mazocruz",direccion=", Carretera Binacional ilo desaguadero, 34 B, Mazocruz",telefono=" (051) 816645",tipo="Comisaria"),
            Contacto(datos="Comisaria del medio ambiente",direccion="Calle Puno 829, Paucarpata 04002",telefono=" (054) 460805",tipo="Comisaria"),
            Contacto(datos="Comisaría PNP Santa Bárbara",direccion="Jiron, Los Cerezos 695, Juliaca 21104",telefono=" 957 687 654",tipo="Comisaria"),
            Contacto(datos="Comisaría Ilave",direccion="W976+PP9, Ilave 21501",telefono="(051) 552414",tipo="Comisaria"),
            Contacto(datos="ATFFS Puno",direccion="Moquegua 276, Puno 21001",telefono=" (051) 367637",tipo="Comisaria"),
            Contacto(datos="Policía Nacional Del Perú",direccion=" C. Puno 829, Miraflores 04001",telefono=" (054) 203298",tipo="Comisaria"),
            Contacto(datos="comisaria SECTORIAL CUSCO",direccion="C. Plateros, Cusco 08002",telefono=" 980 121 879",tipo="Comisaria"),
            Contacto(datos="comisaria SAN SEBASTIAN",direccion="F39F+4FR, 3S, Cusco 08004",telefono="(084) 271890",tipo="Comisaria"),
            Contacto(datos="Comisaría PNP Sectorial Wanchac",direccion="Av 28 de Julio s/n, Cusco 08002",telefono=" (084) 224081",tipo="Comisaria"),
            Contacto(datos="comisaria SIPASPUCYO",direccion="F2H6+CV3, Cusco 08001",telefono=" (084) 249583",tipo="Comisaria"),
            Contacto(datos="comisaria VIVA EL PERÚ cusco",direccion="F26R+HHJ, Cusco 08007",telefono="(084) 249638",tipo="Comisaria"),
            Contacto(datos="COMISARIA SECTORIAL SANTIAGO",direccion=" F2CC+VW4 Av Fortunato L. Herrera, Cusco 08007",telefono="(084) 235700",tipo="Comisaria"),
            Contacto(datos="Comisaría PNP Zarzuela",direccion=" Av. Tupac Amaru- Cusco 08001",telefono="(084) 251396",tipo="Comisaria"),
            Contacto(datos="Comisaría Aeropuerto Alejandro Velazco Astete",direccion="F365+J5Q, Cusco 08006- Aeropuerto Internacional Alejandro Velasco Astete de Cusco",telefono="(084) 232028",tipo="Comisaria"),
            Contacto(datos="Compañia De Bomberos Puno 42",direccion=" Av. El Sol 458- Puno 21001",telefono="(051) 366395",tipo="Bomberos"),
            Contacto(datos="Compañía de Bomberos del Perú - Cusco Nº 39",direccion=" F2GH+XRR- Avenida Garcilaso, Cusco 08002",telefono="(084) 224065",tipo="Bomberos"),
            Contacto(datos="Compañía De Bomberos De San Sebastián",direccion=" Los Saucos 152- Cusco 08006",telefono="(084) 271452",tipo="Bomberos"),
            Contacto(datos="Companía de Bomberos San Jerónimo N° 119",direccion="F42C+F3Q- Cusco 08006",telefono="(084) 277483",tipo="Bomberos"),
            Contacto(datos="Estación de Bomberos Voluntarios Espinar Nro 126",direccion="Av. tintaya- Espinar 08301",telefono=" (084) 301041",tipo="Bomberos"),
            Contacto(datos="Compania de Bomberos Macusani",direccion="Macusani 21251",telefono=" ",tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos de Tarma - 58",direccion="H8H4+MCJ- Tarma 12651",telefono="(064) 321700",tipo="Bomberos"),
            Contacto(datos="BOMBEROS VILLA RICA B-204",direccion="Av Capitan Soto N° 202- Villa Rica 19300",telefono=" (063) 337301",tipo="Bomberos"),
            Contacto(datos="Cia bomberos N 47 Oxapampa",direccion=" Los Colonos- Oxapampa 19231",telefono="(063) 462300",tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos Salvadora Cosmopolita No.17",direccion="8P6W+R26- Av. Circunvalacion Arenales-Cerro De Pasco 19001",telefono="(063) 422475",tipo="Bomberos"),
            Contacto(datos=" Compañía De Bomberos Unión Tingo María N° 61",direccion=" Jr. Lamas 427- Tarapoto 10131",telefono="(061) 563333",tipo="Bomberos"),
            Contacto(datos="Bomberos 219",direccion="RF9J+7H9- Tocache 22540",telefono="965 012 199",tipo="Bomberos"),
            Contacto(datos="Cuerpo de Bomberos Salaverry N29",direccion=" C. Libertad- Salaverry 13611",telefono="(044) 437229(044) 437229",tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos Victor Larco Herrera 224",direccion=" Las Cucardas-Víctor Larco Herrera 13009",telefono="(044) 594473",tipo="Bomberos"),
            Contacto(datos="Hospital Regional Manuel Núñez Butrón",direccion="Av. El Sol 1022- Puno 21002",telefono="(051) 369696",tipo="Centro De Salud"),
            Contacto(datos="Hospital III EsSalud Puno",direccion="4XGX+8VV- Puno 21002",telefono=" (051) 599090",tipo="Centro De Salud"),
            Contacto(datos="Red De Essalud Puno",direccion=" Ilave 738- Puno 21001",telefono="951 712 260",tipo="Centro De Salud"),
            Contacto(datos="Policlínico del Sur SOME SAC",direccion="Tupac Amaru 241- Puno 21001",telefono=" 914 697 536",tipo="Centro De Salud"),
            Contacto(datos="Clínica Puno",direccion="Ramon Castilla 180-Puno 21002",telefono="951 667 705",tipo="Centro De Salud"),
            Contacto(datos="Hospital Regional del Cusco",direccion="F2GW+F39-Cusco 08003",telefono="(084) 231131",tipo="Centro De Salud"),
            Contacto(datos="Hospital SISOL CUSCO",direccion="F38W+XHM-Cusco 08006",telefono="(084) 276494",tipo="Centro De Salud"),
            Contacto(datos="Hospital Nacional Adolfo Guevara Velasco",direccion="F2FR+R3Q- direccion exacta- Cusco",telefono=" (084) 234724",tipo="Centro De Salud"),
            Contacto(datos="HOSPITAL DE LA SOLIDARIDAD - WANCHAQ",direccion="CALLE MICAELA BASTIDAS S/N PLAZA TUPAC AMARU Cusco 08001",telefono="(084) 386060",tipo="Centro De Salud"),
            Contacto(datos="Hospital Antonio Lorena del Cusco",direccion="Cusco 08001",telefono=" 992 837 786",tipo="Centro De Salud"),
            Contacto(datos="Hospital II E Tupac Amaru",direccion="F36Q+JH5-Tinta-Cusco 08006",telefono="941 299 987",tipo="Centro De Salud"),
            Contacto(datos="Hospital Hna. Josefina Serrano",direccion="San Andres 321- Cusco 08002",telefono="232331",tipo="Centro De Salud"),
            Contacto(datos="Centro de Salud San Sebastian",direccion="F38C+X56- Marcos Sapaca- Cusco 08004",telefono="990 667 753",tipo="Centro De Salud"),
            Contacto(datos="Traveler's Clinic O2 Medical Network-Cusco",direccion="Residencial Huancaro- Bellavista C-11, Cusco 08000",telefono="(084) 221213",tipo="Centro De Salud"),
            Contacto(datos="Hospital De Apoyo Palpa",direccion="Independencia 414- Palpa 11331",telefono="(056) 404053",tipo="Centro De Salud"),
            Contacto(datos="ESSALUD Pisco",direccion="Hospital de Pisco-Las Americas 1940, Pisco 1160",telefono="(056) 535550",tipo="Centro De Salud"),
            Contacto(datos="Hospital de Essalud",direccion="GMGQ+RXM- Casma 02661",telefono=" (043) 411110",tipo="Centro De Salud"),
            Contacto(datos="Hospital De Apoyo San Ignacio De Casma",direccion=" GMGW+G32, Casma 02661",telefono="(043) 411299",tipo="Centro De Salud"),
            Contacto(datos="Clinica Bracamonte Casma",direccion=" Avenida Huarmey 167- Pasaje Comercial 104 - 106- Casma 02661",telefono="993 374 533",tipo="Centro De Salud"),
            Contacto(datos="Hospital Regional Eleazar Guzmán Barrón",direccion="VFJJ+M86- Av Brasil, Nuevo Chimbote 02711",telefono="(043) 311608",tipo="Centro De Salud"),
            Contacto(datos="Hospital La Caleta",direccion="Las Casuarinas 201-Chimbote 02803",telefono="(043) 322281",tipo="Centro De Salud"),
            Contacto(datos="EsSalud Hospital III Chimbote",direccion="Av. Circunvalación Del Norte 119, Urb- Laderas del Nte- Chimbote",telefono="(043) 483230",tipo="Centro De Salud"),
            Contacto(datos="EsSalud - Hospital I Cono Sur",direccion="VFGG+7JC- Av. Anchoveta- Chimbote 02711",telefono="(043) 483230",tipo="Centro De Salud"),
            Contacto(datos="Santa Clara",direccion="WCJ8+FW6- Chimbote 02801",telefono="(043) 321485",tipo="Centro De Salud"),
            Contacto(datos="Policlínico Victor Panta Rodríguez",direccion=" Av. Industrial- Chimbote 02803",telefono="(043) 341262",tipo="Centro De Salud"),
            Contacto(datos="Maternidad De Maria",direccion="Av. Enrique Meiggs 2071- Chimbote 02804",telefono="(043) 324171",tipo="Centro De Salud"),
            Contacto(datos="Compañia De Bomberos LAREDO 188",direccion="W25V+2C5- Avenida Trujillo- Laredo 13101",telefono="(044) 446034",tipo="Bomberos"),
            Contacto(datos="Compañia De Bomberos Washington State Nº177",direccion="WX4V+XX3- Trujillo 13006",telefono="(044) 426666",tipo="Bomberos"),
            Contacto(datos="Cuerpo de Bomberos Salaverry N29",direccion="Q2HF+H62-C. Libertad-Salaverry 13611",telefono="(044) 437229",tipo="Bomberos"),
            Contacto(datos="Salvadora Trujillo n°26 - Bomberos",direccion="Av. España 506-558 -Trujillo 13001",telefono="(044) 226495",tipo="Bomberos"),
            Contacto(datos="Compañía de bomberos de La Esperanza",direccion=" Av. Indoamerican y - La Esperanza 13014",telefono="(044) 428021",tipo="Bomberos"),
            Contacto(datos="EXTINPERU SAC",direccion="WW74+4H3 - Huanchaco 13000",telefono=" (044) 282850",tipo="Bomberos"),
            Contacto(datos="Cuerpo General de Bomberos Voluntarios del Perú Cía Salvadora Chiclayo Nº 27",direccion="Héroes Civiles 129 - Chiclayo 14001",telefono="(074) 452997",tipo="Bomberos"),
            Contacto(datos="Cuerpo General de Bomberos Voluntarios Pimentel - Cap. José A. Quiñonez Nº 108",direccion=" 5357+J49 - Av. Grau y Alfonso Ugarte s/n - Rivera del Mar - Pimentel",telefono="(074) 452997",tipo="Bomberos"),
            Contacto(datos="Compañía de Bomberos Salvadora Lambayeque N°88",direccion="Enrique Baca Matos 202 - Lambayeque 14013",telefono=" (074) 283520",tipo="Bomberos"),
            Contacto(datos="Unidad de Bomberos de Ferreñafe",direccion="9647+W7H Ferreñafe 14311",telefono="(074) 286796",tipo="Bomberos"),
            Contacto(datos="B-154 - SALVADORA PICSI",direccion=" Sta. Ana 135 - Distrito de Picsi 14301",telefono="(074) 269129",tipo="Bomberos"),
            Contacto(datos="Compañía De Bomberos BELÉN 41- Iquitos",direccion="6QV2+QX - Jirón Próspero - Iquitos 16006",telefono="(065) 233333",tipo="Bomberos"),
            Contacto(datos="Bomberos San Juan Bautista N°93",direccion="Ca. San Pedro s/n - Iquitos 16008",telefono="(065) 260292",tipo="Bomberos"),
            Contacto(datos="Compañia de Bomberos San Antonio N°94",direccion="Av. Grau 1624 - Iquitos 16001",telefono="(065) 265364",tipo="Bomberos"),
            Contacto(datos="Compañia De Bomberos -Salvadora Punchana B92",direccion="Borja 106 - Iquitos 16003",telefono="(065) 253566",tipo="Bomberos"),
            Contacto(datos="Estacion De Bomberos Voluntarios Del Peru #175 - Nauta",direccion="FCWC+3GP - Nauta 16300",telefono="(065) 411213",tipo="Bomberos"),
            Contacto(datos="Bomberos B-94",direccion="Av. Grau 1720 - Iquitos 16001",telefono="(065) 265384",tipo="Bomberos"),
            Contacto(datos="Hospital De Pomabamba",direccion="5GPP+6HC - Pomabamba 02260",telefono="(043) 451028",tipo="Centro De Salud"),
            Contacto(datos="Hospital de Apoyo Antonio Caldas Dominguez",direccion="5GPP+HJH - Pomabamba 02260",telefono=" (043) 451028",tipo="Centro De Salud"),
            Contacto(datos="Centro Salud Piscobamba",direccion="Prolongación Marcelino Ocaña S/N - Piscobamba 02265",telefono="966 934 877",tipo="Centro De Salud"),
            Contacto(datos="Clínica Medica Especializada Pomabamba",direccion="5GHR+C27- Pomabamba 02260",telefono="999 400 338",tipo="Centro De Salud"),
            Contacto(datos="Centro Odontológico VALE DENT",direccion="Jr. Caraz 310",telefono="965 647 921",tipo="Centro De Salud"),
            Contacto(datos="Red de Salud Conchucos Norte",direccion="Rosendo Vía S/N Pomabamba 02260",telefono="(043) 451003",tipo="Centro De Salud"),
            Contacto(datos="Hospital Leoncio Prado - Huamachuco",direccion="Av. 10 de Julio 209 - Huamachuco 13301",telefono="(044) 441078",tipo="Centro De Salud"),
            Contacto(datos="Hospital Municipal Gloriabamba",direccion="9XM2+J9X - Balta - Cajabamba 06351",telefono="(076) 551286",tipo="Centro De Salud"),
            Contacto(datos="Hospital de Apoyo Cajabamba",direccion= "La Torre 276 - Cajabamba 06351",telefono="(076) 551436",tipo="Centro De Salud"),
            Contacto(datos="ESSALUD Cajamarca",direccion="Santiago Salaverry 101 - Cajabamba 06351",telefono=" (076) 551006",tipo="Centro De Salud"),
            Contacto(datos="Centro Materno NACER",direccion="Jr Ramón Castilla 758 - Huamachuco 13300",telefono="948 451 849",tipo="Centro De Salud"),
            Contacto(datos="Grupo Natividad",direccion="Jr. Salaverry N° 333 - Jr. Hospital N° 233 - 200 - Huamachuco",telefono="(044) 348053",tipo="Centro De Salud"),
            Contacto(datos="C.S. Chuquibamba",direccion="9V85+9PW - Cajabamba 06340",telefono="948 572 264",tipo="Centro De Salud"),
            Contacto(datos="Hospital Juanjui II-E",direccion=" Jr. Arica Cuadra N° 2 - Juanjuí",telefono=" (042) 545910",tipo="Centro De Salud")
        )
        return contactos
    }
}

data class ResponseUser(val contacto: List<Contacto>, val nextPageNumber: Int)